name: Deploy changes to FTP
on:
  push:
    branches: [ "main" ]
jobs:
  copy_to_FTP:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: connect to FTP
        env: 
          SRC_PATH: "/home/mikis/my_project/for_devops"
          DEST_PATH: "/home/mikis/path/to/"
          SECRET_USER: ${{ secrets.UserName }}
          SECRET_PASS: ${{ secrets.Password }}
        run: |
          cd $SRC_PATH
          ftp -i ftp://$SECRET_USER:$SECRET_PASS@mydebian<<END_TASK
          cd $DEST_PATH
          mput *
          exit
          END_TASK

      - name: Get git info 
        run: |
          git log > VERSION.txt
          git branch -v >> VERSION.txt


