name: Deploy changes to FTP
on:
  push:
    branches: [ "main" ]
jobs:
  copy_to_FTP:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: connect to FTP
        env: 
          DEST_PATH: "/path/to/"
          SECRET_USER: ${{ secrets.UserName }}
          SECRET_PASS: ${{ secrets.Password }}
        run: |
          ftp -i ftp://$SECRET_USER:$SECRET_PASS@ftp.com<<END_TASK
          cd $DEST_PATH
          mput *
          exit
          END_TASK

      - name: Get git info 
        run: |
          git log > VERSION.txt
          git branch -v >> VERSION.txt
