name: Deploy changes to FTP
on:
  push:
    branches: [ "main" ]
jobs:
  copy_to_FTP:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: connect to FTP
        env: 
          SECRET_USER: ${{ secrets.UserName }}
          SECRET_PASS: ${{ secrets.Password }}
        run: pwd >> /tmp/sdjfakfjhak

      - name: Get git info 
        run: |
          git log > VERSION.txt
          git branch -v >> VERSION.txt
#          ftp ftp://"$env:SECRET_USER":"$env:SECRET_PASS"@ftp.com<<END_TASK
#          mput *
#          exit
#          END_TASK

